### ISSUE TITLE
[BUG] Vertex AI Gemini models cause a ManagedChannel allocation site due channel to not being shutdown

### ISSUE THREAD

**Issue by kappamax** [langchain4j/langchain4j#1090] opened 2024-05-11 04:54 UTC
**Describe the bug**
When I repeated call the gemini model to execute from my application code, I get this message. It does run the execution, and the underlying code garbage collects itself, but maybe we have to call shutdown from without langchain4j as well.

**Log and Stack trace**
```
i.g.i.ManagedChannelOrphanWrapper        : *~*~*~ Previous channel ManagedChannelImpl{logId=25, target=us-east4-aiplatform.googleapis.com:443} was garbage collected without being shut down! ~*~*~*
    Make sure to call shutdown()/shutdownNow()

java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:672) ~[grpc-core-1.62.2.jar:1.62.2]
	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:260) ~[grpc-api-1.62.2.jar:1.62.2]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:442) ~[gax-grpc-2.45.0.jar:2.45.0]
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:107) ~[gax-grpc-2.45.0.jar:2.45.0]
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:85) ~[gax-grpc-2.45.0.jar:2.45.0]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:243) ~[gax-grpc-2.45.0.jar:2.45.0]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:237) ~[gax-grpc-2.45.0.jar:2.45.0]
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:226) ~[gax-2.45.0.jar:2.45.0]
	at com.google.cloud.vertexai.api.stub.GrpcPredictionServiceStub.create(GrpcPredictionServiceStub.java:295) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.api.stub.PredictionServiceStubSettings.createStub(PredictionServiceStubSettings.java:319) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.api.PredictionServiceClient.<init>(PredictionServiceClient.java:427) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.api.PredictionServiceClient.create(PredictionServiceClient.java:409) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.VertexAI.getPredictionServiceClient(VertexAI.java:289) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.generativeai.GenerativeModel.generateContent(GenerativeModel.java:629) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.generativeai.GenerativeModel.generateContent(GenerativeModel.java:610) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at com.google.cloud.vertexai.generativeai.GenerativeModel.generateContent(GenerativeModel.java:499) ~[google-cloud-vertexai-0.6.0.jar:0.6.0]
	at dev.langchain4j.model.vertexai.VertexAiGeminiChatModel.lambda$generate$0(VertexAiGeminiChatModel.java:109) ~[langchain4j-vertex-ai-gemini-0.30.0.jar:na]
	at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192) ~[langchain4j-core-0.30.0.jar:na]
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229) ~[langchain4j-core-0.30.0.jar:na]
	at dev.langchain4j.model.vertexai.VertexAiGeminiChatModel.generate(VertexAiGeminiChatModel.java:108) ~[langchain4j-vertex-ai-gemini-0.30.0.jar:na]
```

**To Reproduce**

In my case, I've just called `model.generate(...)` a few times with a complex prompt (i.e. > timeout

**Expected behavior**

This message should not pop up using gemini.

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: gemini-1.5-pro-preview-0409
- Java version: OpenJDK Runtime Environment Corretto-11.0.22.7.1
- Spring Boot version (if applicable): 3.2.5 (also happed on 3.2.4)

**Additional context**

**Comment by langchain4j** [comment] 2024-05-13 08:22
@kappamax thank you a lot for reporting!

cc @glaforge

**Comment by glaforge** [comment] 2024-05-23 19:58
@kappamax if you upgrade to the new 0.31 version released today, this problem should be gone.
Could you please double check that you're not seeing it anymore? (and then we can close this ticket)

**Comment by langchain4j** [comment] 2024-06-11 13:01
Fixed in 0.31.0

**Closed as completed by langchain4j** 2024-06-11 13:01 UTC
Labels: bug, P2, P3, Gemini

**Comment by yushengliao** [comment] 2024-06-18 01:13
@glaforge
I still encountered this issue while using 0.31.0

 - *~*~*~ Previous channel ManagedChannelImpl{logId=1, target=124.***.**.240:19530} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:655)
	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:261)
	at io.milvus.client.MilvusServiceClient.<init>(MilvusServiceClient.java:143)
	at dev.langchain4j.store.embedding.milvus.MilvusEmbeddingStore.<init>(MilvusEmbeddingStore.java:83)
	at dev.langchain4j.store.embedding.milvus.MilvusEmbeddingStore$Builder.build(MilvusEmbeddingStore.java:329)
	at org.dromara.wenxiaoqi.demo.pm.T2controller.m(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:141)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.dromara.wenxiaoqi.demo.pm.T2controller$$SpringCGLIB$$0.m(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.dromara.common.web.filter.RepeatableFilter.doFilter(RepeatableFilter.java:30)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.dromara.common.encrypt.filter.CryptoFilter.doFilter(CryptoFilter.java:42)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by glaforge** [comment] 2024-06-18 05:33
I don't see any trace related to Vertex AI Gemini.

It seems that it's Milvus causing this:

`dev.langchain4j.store.embedding.milvus.MilvusEmbeddingStore$Builder.build(MilvusEmbeddingStore.java:329)`

**Comment by wjbeau** [comment] 2024-07-30 09:06
@glaforge I am seeing this error on 0.31.0.  Here's my stacktrace which seems to mention langchain4j.mode.vertexai.VertexAiGeminiModel:

```
*~*~*~ Previous channel ManagedChannelImpl{logId=56, target=us-west1-aiplatform.googleapis.com:443} was garbage collected without being shut down! ~*~*~*
    Make sure to call shutdown()/shutdownNow()
java.lang.RuntimeException: ManagedChannel allocation site
    at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:102)
    at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:60)
    at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:51)
    at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:672)
    at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:260)
    at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:442)
    at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:107)
    at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:85)
    at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:243)
    at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:237)
    at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:226)
    at com.google.cloud.vertexai.api.stub.GrpcPredictionServiceStub.create(GrpcPredictionServiceStub.java:295)
    at com.google.cloud.vertexai.api.stub.PredictionServiceStubSettings.createStub(PredictionServiceStubSettings.java:319)
    at com.google.cloud.vertexai.api.PredictionServiceClient.<init>(PredictionServiceClient.java:427)
    at com.google.cloud.vertexai.api.PredictionServiceClient.create(PredictionServiceClient.java:409)
    at com.google.cloud.vertexai.VertexAI.newPredictionServiceClient(VertexAI.java:285)
    at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:186)
    at com.google.cloud.vertexai.VertexAI.getPredictionServiceClient(VertexAI.java:274)
    at com.google.cloud.vertexai.generativeai.GenerativeModel.generateContent(GenerativeModel.java:391)
    at com.google.cloud.vertexai.generativeai.GenerativeModel.generateContent(GenerativeModel.java:378)
    at dev.langchain4j.model.vertexai.VertexAiGeminiChatModel.lambda$generate$0(VertexAiGeminiChatModel.java:114)
    at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:192)
    at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
    at dev.langchain4j.model.vertexai.VertexAiGeminiChatModel.generate(VertexAiGeminiChatModel.java:113)
    at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:144)
    at jdk.proxy2/jdk.proxy2.$Proxy304.chat(Unknown Source)
   ...
```

It seems from my reading of the stacktrace that this is somehow being caused in the depths of the generated agent proxy.  Do I need to do anything to enable a graceful shutdown somehow?

**Comment by glaforge** [comment] 2024-07-30 10:04
@wjbeau could you please show a bit of your code, how you're using the Gemini model instance?
You could try release 0.33, but I think it's indeed in 0.31 that I worked on that issue, so 0.31 should have been good.

Another thing you can try: 
The `VertexAiGeminiChatModel` implements `Closeable`. So you could use a `try` with resources approach to handle the lifecycle of the object (and the underlying `VertexAI` object which is also `AutoCloseable`).

**Comment by wjbeau** [comment] 2024-07-30 10:15
Sure, the code in question is pretty simple (as far as the langchain4j integration is concerned).  Basically I have an interface called AIAssistant:

```
public interface AIAssistant {

    @SystemMessage ("You are a helpful assistant")
    Result<String> chat(@UserMessage String prompt);
}
```

I then create such an assistant with code that looks something like:

```
public ChatLanguageModel createGemini2AIAssistant() {
        return VertexAiGeminiChatModel.builder()
                .project(config.getGemini().getProject())
                .location(config.getGemini().getLocation())
                .modelName(config.getGemini().getModel())
                .temperature((float) config.getGemini().getTemperature())
                .build();
    }
    ...
var model = switch (provider) {
            case OPENAI -> createOpenAIAssistant();
            case ANTHROPIC -> createAnthropicAIAssistant();
            case OLLAMA -> createOllamaAIAssistant();
            case GEMINI -> createGemini2AIAssistant();
        };

        var builder = AiServices.builder(AIAssistant.class)
            .chatLanguageModel(model);
        if (contentRetriever != null) {
            builder = builder.contentRetriever(contentRetriever);
        }

        return builder.chatMemory(MessageWindowChatMemory.withMaxMessages(50))
            .build();
```

And then I invoke that instance with something like:

```
...
Prompt prompt = StructuredPromptProcessor.toPrompt(submissionDetails);

            log.info("GenericPromptVerificationHandler Prompt: {}", prompt);
            var response = assistant.chat(prompt.toUserMessage().singleText());

            String jsonPart = extractJson(response.content());
...
```

It is the call to assistant.chat that is causing the exception.  This is all happening inside a SpringBoot server that's deployed and I'm just seeing those messages in the server logs.  I haven't been able to reproduce this.  I'd be happy to use the AutoCloseable but I'm just passing it to the AiServices.builder so is the intention that I handle the closing of it after I'm done with the proxy instance?

I'll definitely upgrade to 0.33 anyway to see if that helps

**Comment by glaforge** [comment] 2024-07-30 10:27
@wjbeau I wish we were able to create a reproducer, because the stacktrace shows bits that are not directly related to my implementation. So it's hard to really figure out what's going on. 

As your code is quite generic (ie. working with different providers), and going through `AiServices`, I think once you're done with calling the proxy instance, you could add something like:
```java
if (model instanceof Closeable) {
    Closeable closeable = (Closeable)model;
    closeable.close();
}
```

If you're trying this, and the error goes away, I'd be interested in hearing about it.
I'd add some details to the JavaDocs with this advice.

An approach with `AiServices` could be to add such a `close()` call there, but maybe users could reuse the underlying model used in `AiServices`, so it's not ideal to close something that someone wants to reuse afterwards.

**Comment by wjbeau** [comment] 2024-07-30 11:23
Yes I think the cleanest solution might be to allow the interface provided to the builder to implement AutoCloseable and if it does have the proxy implement it.  Then I could maybe do something like

```
try (var assistant = builder.chatMemory(MessageWindowChatMemory.withMaxMessages(50)).build()) {
  assitant.chat();
}
```

**Comment by wjbeau** [comment] 2024-07-30 11:30
The problem I have in my implementation is that the AIAssistant instance is created by a factory class (since I have support for different LLMs) and the caller just uses the implementation.  So the factory, which creates the reference to the model has no knowledge of when the work is completed and the caller has no reference to the model to call close.  I'll have to build some kind of reference map so I can get the model back later and close it.  I'll give it a shot and see what I come up with.  Let me  take a look at the langchain4j code - maybe I can see where my use is falling fowl and open a PR or something.

**Comment by wjbeau** [comment] 2024-07-30 11:57
@glaforge sorry having trouble getting the langchain4j project to build atm - some maven thing.  Would something like this be an option in DefaultAiServices (untested):

```
        Object proxyInstance = Proxy.newProxyInstance(
                context.aiServiceClass.getClassLoader(),
                new Class<?>[]{context.aiServiceClass, AutoCloseable.class},
                new InvocationHandler() {

                    private final ExecutorService executor = Executors.newCachedThreadPool();

                    @Override
                    public Object invoke(Object proxy, Method method, Object[] args) throws Exception {

                        if (method.getDeclaringClass() == Object.class) {
                            // methods like equals(), hashCode() and toString() should not be handled by this proxy
                            return method.invoke(this, args);
                        }

                        if (method.getDeclaringClass() == AutoCloseable.class) {
                            executor.shutdown();
                            if (context.chatModel instanceof Closeable) {
                                ((Closeable) context.chatModel).close();
                            }
                            return null;
                        }
```

**Comment by glaforge** [comment] 2024-07-30 12:45
@wjbeau Yes, exactly, something along those lines.

The downside I see with this approach, as I hinted in my previous comment, is that we always _close_ the model after its use with `AiServices`. However, `AiServices` doesn't _own_ the model instance, and that model instance could be reused afterwards (instead of creating a new instance each time for each use)

I'll have to discuss this idea with @langchain4j to get his thoughts.

That said, maybe I could also tweak the Gemini module implementation to notice that it has been closed to re-instantiate the underlying closeable object (`VertexAi` object which handles the connection with the model API). It might be worth investigating...

**Comment by wjbeau** [comment] 2024-07-30 13:00
I see, yes that makes sense.  I hopefully solved it in my case by just writing a little wrapper for my assistant instance which implements autocloseable and shuts down the model as needed.  I'll let you know if I see any more issues.

**Comment by RyanHowell30** [comment] 2025-01-09 12:52
@wjbeau Hey man, did you by any chance solve this? I am seeing the same issue using Spring AI and the VertexAiTextEmbeddingModel

**Comment by wjbeau** [comment] 2025-01-09 14:01
@RyanHowell30 I honestly don't remember the details now.  We ended up switching to Spring AI too and didn't have the issue there.  What I think I did was wrap the model in a class that implemented Closeable and used a try-with-resources block or manually called close or something, which in turn shut down the model.  But I can't remember the details now.

**Comment by glaforge** [comment] 2025-01-09 14:29
Wrapping the use of the model with a try/with resources should prevent this behavior.
But this error is just a warning that is logged and doesn't prevent you from using the model as expected.

**Comment by RyanHowell30** [comment] 2025-01-09 15:08
@wjbeau @glaforge thanks gents. But I see the chat model and multimodal embeding models have close(). It is just the VertexAiTextEmbeddingModel which causes the warning. I created a ticket on Spring AI, hopefully there is a fix. 

The root cause of the unclosed channel errors is that Spring AI’s VertexAiTextEmbeddingModel creates a new PredictionServiceClient on each call, never calling close().

**Comment by charlie-ang-collibra** [comment] 2025-01-28 22:28
Hello.  I am using Spring AI's version of VertexAITextEmbeddingModel.   It doesn't implement Closeable.   How else can I manage this error?

Sorry.  I'll also post my question on the Spring AI github.

🙏

**Comment by glaforge** [comment] 2025-01-29 07:39
@charlie-ang-collibra You'll have to ask the Spring AI developers how you can handle that in their framework. There's nothing we can do on our side.
