### ISSUE TITLE
[BUG] Ai Service add informations to the query..

### ISSUE THREAD

**Issue by andr3aLucch3si85** [langchain4j/langchain4j#628] opened 2024-02-12 14:00 UTC
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

I implemented chat model with content retriever but it seems that the agent adds information from embedded documents.

Example

User: Ciao mi chiamo Andrea
Original query: 'Ciao mi chiamo Andrea'
Transformed queries: - 'Ciao mi chiamo Andrea'

- body: {
  "model": "gpt-3.5-turbo-0125",
  "messages": [
    {
      "role": "user",
      "content": "Ciao mi chiamo Andrea\n\nAnswer using the following information:\nRiccardo Manconi."
    }
  ],
  "temperature": 0.0,
  "max_tokens": 256
}

It seems that the agent interprets first input like a question and try to answer it.
How can I avoid this behavior?

**Please complete the following information:**
- LangChain4j version: 0.27.1
- Java version: 17
- Spring Boot version (if applicable): 3.2.2

**Comment by langchain4j** [comment] 2024-02-22 15:13
Hi @andr3aLucch3si85 the fact that information from documents is added is a feature, not a bug :)

Another question is how to avoid retrieving irrelevant information OR make the assistant ignore irrelevant information.

2 things from the top of my mind:
1. try lowering `minScore` parameter in `EmbeddingStoreContentRetriever` to filter out irrelevant segments
2. try using `LanguageModelQueryRouter` which can route to NO retrievers (basically skipping retrival step). [Example](https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_03_Advanced_RAG_with_Query_Routing.java)

I am closing this issue as this is not a bug. Feel free to open a [discussion on github](https://github.com/langchain4j/langchain4j/discussions) or on [discord](https://discord.gg/JzTFvyjG6R)

**Closed as completed by langchain4j** 2024-02-22 15:13 UTC
Labels: bug
