### ISSUE TITLE
[FEATURE] Implement embedding removal methods for Azure AI Search embedding store

### ISSUE THREAD

**Issue by JSON-OBJECT** [langchain4j/langchain4j#1311] opened 2024-06-18 01:58 UTC
**Is your feature request related to a problem? Please describe.**
If the document deletion feature is added to Azure AI Search in LangChain4j, we will be able to remove specific documents that are no longer needed using only the abstracted LangChain4j interface. (Currently, the Azure AI Search REST API is being used separately for document deletion.)

**Additional context**
https://learn.microsoft.com/en-us/rest/api/searchservice/addupdate-or-delete-documents

**Comment by suvaidkhan** [comment] 2024-07-03 17:55
Hi is this up for grabs?
If yes, I'd love to take a stab at it.

**Comment by langchain4j** [comment] 2024-07-04 07:13
@suvaidkhan sure, go ahead!

**Comment by suvaidkhan** [comment] 2024-07-06 12:58
Thanks @langchain4j 
Would I be correct in assuming that the changes would look quite similar to this PR - https://github.com/langchain4j/langchain4j/pull/1196/files

**Comment by langchain4j** [comment] 2024-07-08 08:38
@suvaidkhan yes, but for ITs, you can simply extend from `EmbeddingStoreWithRemovalIT`

**Comment by suvaidkhan** [comment] 2024-07-08 19:38
@langchain4j  Couple of questions re ITs -
Azure AI search doesnt have a testcontainer, so I'm assuming the ITs will be written in the style of `AzureAiSearchEmbeddingStoreIT` class.

Also what should be the values of AZURE_SEARCH_ENDPOINT and AZURE_SEARCH_KEY for running ITs in the `AzureAiSearchEmbeddingStoreIT` class.
Thanks!

**Comment by langchain4j** [comment] 2024-07-10 08:32
> Azure AI search doesnt have a testcontainer, so I'm assuming the ITs will be written in the style of AzureAiSearchEmbeddingStoreIT class.

If you mean that a cloud instance of Azure AI Search should be used in the IT, then yes.

> Also what should be the values of AZURE_SEARCH_ENDPOINT and AZURE_SEARCH_KEY for running ITs in the AzureAiSearchEmbeddingStoreIT class.

`AZURE_SEARCH_ENDPOINT` for me is `https://langchain4j-ai-search.search.windows.net`, but it will be different for you. You need to have an Azure account and create AI Search deployment.
`AZURE_SEARCH_KEY` is secret :)

**Comment by langchain4j** [comment] 2024-08-06 09:43
Duplicate of https://github.com/langchain4j/langchain4j/issues/1467

**Closed as completed by langchain4j** 2024-08-06 09:43 UTC
Labels: enhancement, good first issue, P2, Azure
