### ISSUE TITLE
[FEATURE] Support for PDF summarization using map-reduce

### ISSUE THREAD

**Issue by sjivan** [langchain4j/langchain4j#1377] opened 2024-06-28 17:16 UTC
I'd like to summarize a large pdf document. Langchain supports doing this using map-reduce

https://python.langchain.com/v0.2/docs/tutorials/summarization/

**Comment by langchain4j** [comment] 2024-07-04 15:34
Duplicate of https://github.com/langchain4j/langchain4j/issues/121

**Closed as completed by langchain4j** 2024-07-04 15:34 UTC
Labels: enhancement, P2, P3
