### ISSUE TITLE
[BUG] Maven直接使用langchain4j的jar包调用流式（Stream）输出时，会有okhttp依赖包的问题导致调用失败。去除默认的okhttp版本（3.14.9）换为例如4.9.3的版本后，可以完成调用

### ISSUE THREAD

**Issue by wuyuhuangquan** [langchain4j/langchain4j#1038] opened 2024-04-30 02:13 UTC
**Describe the bug**

使用langchainjar包默认okhttp的依赖（3.14.9），会导致调用大模型流式输出失败；更换okhttp依赖版本（4.9.3）后，可以成功实现流式输出。

**Log and Stack trace**

Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
	at dev.langchain4j.model.qianfan.client.StreamingRequestExecutor.stream(StreamingRequestExecutor.java:89)
	at dev.langchain4j.model.qianfan.client.StreamingRequestExecutor.access$000(StreamingRequestExecutor.java:17)
	at dev.langchain4j.model.qianfan.client.StreamingRequestExecutor$1$1$1.execute(StreamingRequestExecutor.java:45)
	at dev.langchain4j.model.qianfan.QianfanStreamingChatModel.generate(QianfanStreamingChatModel.java:134)
	at dev.langchain4j.model.qianfan.QianfanStreamingChatModel.generate(QianfanStreamingChatModel.java:86)
	at dev.langchain4j.model.chat.StreamingChatLanguageModel.generate(StreamingChatLanguageModel.java:25)
	at generator.test$StreamingLanguageModel_Example.main(test.java:57)

**To Reproduce**

public static void main(String[] args) {
            // Sorry, "demo" API key does not support streaming (yet). Please use your own key.
//            StreamingLanguageModel model = OpenAiStreamingLanguageModel.builder()
//                    .apiKey(ApiKeys.OPENAI_API_KEY)
//                    .baseUrl(ApiKeys.OPENAI_BASE_URL)
//                    .modelName("gpt-3.5-turbo")
//                    .temperature(0.7).build();
            QianfanStreamingChatModel model = QianfanStreamingChatModel.builder()
                    .apiKey(ApiKeys.BAIDU_API_KEY)
                    .secretKey(ApiKeys.BAIDU_SECRET_KEY)
                    .modelName("ERNIE-Bot")
                    .temperature(0.01)
                    .build();

            model.generate("帮我写一篇500字的秋游总结", new StreamingResponseHandler<AiMessage>() {
                @Override
                public void onNext(String s) {
                    System.out.print(s);
                }

                @Override
                public void onError(Throwable throwable) {
                    throw new RuntimeException(throwable);
                }
            });
        }

**Expected behavior**

更换langchain4j默认okhttpjar包依赖版本，消除此BUG，

**Please complete the following information:**
- LangChain4j version:0.30.0
- LLM(s) used: ERNIE-Bot(百度文心)
- Java version: 1.8.0_241
- Spring Boot version (if applicable): 2.4.3

**Additional context**

**Comment by langchain4j** [comment] 2024-04-30 09:40
@wuyuhuangquan LangChain4j uses okhttp 4.12.0, where did you get 3.14.9 and 4.9.3 from?

**Comment by langchain4j** [comment] 2024-04-30 09:42
Duplicate of https://github.com/langchain4j/langchain4j/issues/1039

**Closed as completed by langchain4j** 2024-04-30 09:42 UTC
Labels: bug
