### ISSUE TITLE
Our company currently uses Xinference more frequently. Will the author consider supporting Xinference models in the future?

### ISSUE THREAD

**Issue by cherryhuahua** [langchain4j/langchain4j#1941] opened 2024-10-17 06:18 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment] 2024-10-17 07:20
Duplicate of [Xinference](https://github.com/langchain4j/langchain4j/issues/1179)

**Closed as completed by langchain4j** 2024-10-17 07:20 UTC
Labels: enhancement
