### ISSUE TITLE
[FEATURE] Support Markdown document splitter

### ISSUE THREAD

**Issue by xigexb** [langchain4j/langchain4j#1227] opened 2024-06-04 09:04 UTC
支持Markdown格式文档

**Comment by thesteve0** [comment] 2024-06-09 00:15
@langchain4j can you please assign this to me for now

**Comment by langchain4j** [comment] 2024-07-04 15:25
Duplicate of https://github.com/langchain4j/langchain4j/issues/574

**Closed as completed by langchain4j** 2024-07-04 15:25 UTC
Labels: enhancement, P2

**Comment by thesteve0** [comment] 2024-07-30 00:43
Hey - I haven't forgot about this but I went on Holiday and now my paid consulting work is piled up. Sorry for the delay - please feel free to reassign if needed
