### ISSUE TITLE
[FEATURE] When returning TokenStream, the List<Content>can be obtained

### ISSUE THREAD

**Issue by hzkitty** [langchain4j/langchain4j#1550] opened 2024-07-31 09:14 UTC
When using TokenStream for streaming returns, how to obtain the reference source of the question and answer is to retrieve the List<Content>returned by the retrieve method in ContentRetriever

**Comment by langchain4j** [comment] 2024-08-05 14:17
Duplicate of https://github.com/langchain4j/langchain4j/issues/660

**Closed as completed by langchain4j** 2024-08-05 14:17 UTC
Labels: enhancement
