### ISSUE TITLE
[FEATURE] should we add a “ReturnAsOutput” Annotation on Tool funtion to reduce LLM model requests

### ISSUE THREAD

**Issue by BiyoTech** [langchain4j/langchain4j#1246] opened 2024-06-07 11:24 UTC
when we use tools ,we send request llm 3 times, e.g:
 {
            "role": "user",
            "content": "What's the weather like in Shanghai today？"
        },
        {
            "role": "assistant",
            "content": null,
            "function_call": {
                "name": "get_current_weather",
                "arguments": "{ \"location\": \"shanghai\"}"
            }
        },
        {
            "role": "function",
            "name": "get_current_weather",
            "content": "{\"temperature\": \"25\", \"unit\": \"摄氏度\", \"description\": \"晴朗\"}"
        },
        {
            "role": "assistant",
            "content": "It's 25 degrees Celsius and sunny in Shanghai today"
        },

I think we should give user a choice to add a  a “ReturnAsOutput” Annotation on get_current_weather method, let DefaultAiServices  just return get_current_weather execution result,. like this:
@Tool("get weather information by location")
    @ReturnAsOutput
    String get_current_weather(@P("location")String location) {
        return "It's 25 degrees Celsius and sunny in Shanghai today"
    }
 and  in DefaultAiServices.java ,add code below:
if (method.isAnnotationPresent(ReturnAsOutput.class)) {
                                String result = toolExecutor.getToolExecuteResult();
                                chatMemory.add(AiMessage.aiMessage(result));
                                return result;
                            }
                            response = context.chatModel.generate(chatMemory.messages(), context.toolSpecifications);

**Comment by langchain4j** [comment] 2024-06-10 12:03
Hi, thank you!
Closing this issue as it is a duplicate of https://github.com/langchain4j/langchain4j/issues/124

**Closed as completed by langchain4j** 2024-06-10 12:03 UTC
Labels: enhancement
