### ISSUE TITLE
[BUG] assistant.chat(question) fails on Android because of a regex error in DefaultPromptTemplateFactory

### ISSUE THREAD

**Issue by garciaraul85** [langchain4j/langchain4j#1212] opened 2024-05-31 14:20 UTC
**Describe the bug**
I've been working with the assistants using kotlin. Using this simple code:
`  

        val model: ChatLanguageModel = OpenAiChatModel.builder()
       . apiKey(API_KEY)
    .logRequests(true)
    .build()

        val assistant: Assistant = AiServices.builder(Assistant::class.java)
            .chatLanguageModel(model)
            .build()

        val question = "Tell me a joke"
        val answer = assistant.chat(question)
        println(answer)
`
When I run it from a main method in kotlin it works as expected, but if I run the exact same code on an Android app I get the following logs:

**Log and Stack trace**
`Process: com.example.myapplication, PID: 19711
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at dev.langchain4j.model.input.DefaultPromptTemplateFactory.create(DefaultPromptTemplateFactory.java:18)
                                                                                                    	at dev.langchain4j.model.input.DefaultPromptTemplateFactory.create(DefaultPromptTemplateFactory.java:14)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.<init>(PromptTemplate.java:62)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.<init>(PromptTemplate.java:51)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.from(PromptTemplate.java:126)
                                                                                                    	at dev.langchain4j.service.DefaultAiServices.prepareUserMessage(DefaultAiServices.java:288)
                                                                                                    	at dev.langchain4j.service.DefaultAiServices.access$200(DefaultAiServices.java:33)
                                                                                                    	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:95)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy3.chat(Unknown Source)
                                                                                                    	at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:51)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8767)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8745)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 10
                                                                                                    \{\{(.+?)}}
                                                                                                              ^
                                                                                                    	at com.android.icu.util.regex.PatternNative.compileImpl(Native Method)
                                                                                                    	at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:53)
                                                                                                    	at com.android.icu.util.regex.PatternNative.create(PatternNative.java:49)
                                                                                                    	at java.util.regex.Pattern.compile(Pattern.java:3533)
                                                                                                    	at java.util.regex.Pattern.<init>(Pattern.java:1419)
                                                                                                    	at java.util.regex.Pattern.compile(Pattern.java:921)
                                                                                                    	at dev.langchain4j.model.input.DefaultPromptTemplateFactory$DefaultTemplate.<clinit>(DefaultPromptTemplateFactory.java:23)
                                                                                                    	... 28 more`

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: ChatGPT
- Java version: 8
- Spring Boot version (if applicable): 

**Additional context**
According to ChatGPT itself:The difference in behavior between running the code in a standalone Java application (such as a main method) and running it in an Android environment is likely due to differences in the underlying regular expression libraries and their handling of patterns.

In Android, the regex library may be stricter or have different implementation details compared to the standard Java regex library used in desktop or server environments. This can cause a pattern that works in one environment to fail in another.

To ensure compatibility across both environments, it’s important to use fully escaped patterns and follow best practices for regex usage. The corrected pattern should be `\\{\\{(.+?)\\}\\}`  instead of` \{\{(.+?)}}`

**Comment by langchain4j** [comment] 2024-06-03 07:37
@garciaraul85 thank you!
This is a duplicate of https://github.com/langchain4j/langchain4j/issues/1075
Could you open a PR with the fix please?

**Comment by garciaraul85** [comment] 2024-06-03 13:58
on which branch does the pr go?

**Comment by langchain4j** [comment] 2024-06-03 14:32
@garciaraul85 you can fork the repo and use any branch (main or feature branch)

**Comment by langchain4j** [comment] 2024-07-25 17:17
Fixed by https://github.com/langchain4j/langchain4j/pull/1518

**Closed as completed by langchain4j** 2024-07-25 17:17 UTC
Labels: bug, P2, Android
