### ISSUE TITLE
[FEATURE] Add summarization methods for documents

### ISSUE THREAD

**Issue by InAnYan** [langchain4j/langchain4j#818] opened 2024-03-23 21:23 UTC
**Is your feature request related to a problem? Please describe.**
No, this feature is not related to a problem.

**Describe the solution you'd like**
In `langchain` there are three methods for documents summarization: `Stuffing`, `MapReduce`, and `Refine`. It would be cool if they were in `langchain4j`.

**Describe alternatives you've considered**
Unapplicable for this feature.

**Additional context**
A useful link: [https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-summarization/summarization_large_documents_langchain.ipynb](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/use-cases/document-summarization/summarization_large_documents_langchain.ipynb).

**Comment by langchain4j** [comment] 2024-04-09 07:12
Hi, did you consider using long-context LLMs for summarization tasks?

**Comment by langchain4j** [comment] 2024-04-17 14:34
Duplicate of https://github.com/langchain4j/langchain4j/issues/121

**Closed as completed by langchain4j** 2024-04-17 14:34 UTC
Labels: enhancement
