### ISSUE TITLE
[BUG]  Pinecone Embedding store not saving TextSegment metadata

### ISSUE THREAD

**Issue by rgrebski** [langchain4j/langchain4j#948] opened 2024-04-16 16:43 UTC
**Describe the bug**
PineconeEmbeddingStore is not saving TextSegment metadata to Pinecone. It simply ignores custom metadata ([see the code](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java#L136))

**Log and Stack trace**
N/A

**To Reproduce**
Try to ingest a document with custom metadatada into Pinecone

**Expected behavior**
Custom metadata is saved

**Please complete the following information:**
- LangChain4j version: 0.29.1
- LLM(s) used: ChatGPT 3.5 Turbo
- Java version: 19
- Spring Boot version (if applicable): N/A

I can provide PR once this issue is confirmed.

**Comment by langchain4j** [comment] 2024-04-17 06:41
Hi @rgrebski thanks for reporting!
Closing this as a duplicate of https://github.com/langchain4j/langchain4j/issues/435

**Closed as completed by langchain4j** 2024-04-17 06:41 UTC
Labels: bug
