### ISSUE TITLE
[FEATURE] Classify embeddings in store.

### ISSUE THREAD

**Issue by AbdullahGheith** [langchain4j/langchain4j#207] opened 2023-10-03 20:24 UTC
Would really love if we could classify the data stored in the embeddingstore.

for instance if i have 2 books, i want to be able to put them both into the embeddingsstore, and always know what book the information comes from

**Comment by langchain4j** [comment] 2023-10-06 19:53
Hi @AbdullahGheith, you can do this already. Each Document and TextSegment has Metadata associated with it (for example, the file/url it comes from, etc). You can also add more metadata manually if you want. Some of the EmbeddingStore implementations can store and retrieve Metadata along with the text. So when you get TextSegment from the EmbeddingStore, check the Metadata and see where this segment comes from. BTW TextSegment inherits all Metadata from Document during splitting. Milvus, Pinecone, Vespa and Weaviate do not support this (this is an incomplete implementation on our side), but the rest of the stores do support: Cassandra, Chroma, Elasticsearch, Redis and our own InMemoryEmbeddingStore.

**Comment by AbdullahGheith** [comment] 2023-10-06 19:55
Is it also possible when searching with findRelevant to filter out what metadata we are searching for?

If maxresults is set to 3, I don't want to waste 2 of them on an irrelevant document.

**Comment by langchain4j** [comment] 2023-10-06 20:10
@AbdullahGheith metadata filtering is still not supported, but this is a feature with a high priority, will work on it soon. For the moment I can suggest to use multiple EmbeddingStores and split documents between them. So Document1 goes to EmbeddingStore1 and Document2 goes to EmbeddingStore2. Not ideal, but this will work.

**Comment by AbdullahGheith** [comment] 2023-10-06 20:11
Thx I will wait. This is not possible for me because I have potentially 100+ documents

**Comment by langchain4j** [comment] 2023-10-06 20:22
@AbdullahGheith it would help if you coud describe your use case in details, this will help during designing and implementation

**Comment by AbdullahGheith** [comment] 2023-10-06 20:27
I want to classify every house in the area so the customer can chat about the house and ask questions like "how big is it?"

Now naturally, this data has been classified (for this specific property) and saved in its own metadata for that house, including all the other data about this house.

So when the user asks "how big is it", I want to filter all the other metadata off and only search this house.

**Comment by langchain4j** [comment] 2023-10-06 20:37
So information about each house is initially in a separate document, right? Then during search you want to search for text segments with content similar to "how big is it" only for one specific document, right?

**Comment by AbdullahGheith** [comment] 2023-10-06 20:38
Exactly

**Comment by Heezer** [comment] 2023-10-17 10:34
Sound like duplicate of #151

**Comment by langchain4j** [comment] 2024-03-12 07:55
Yes, this is a duplicate.

[Metadata filtering](https://github.com/langchain4j/langchain4j/pull/610) is now supported in version 0.28.0 for `InMemoryEmbeddingStore`, `MilvusEmbeddingStore` and `ElasticsearchEmbeddingStore`. You are welcome to contribute support for the remaining EmbeddingStores!

**Closed as completed** 2024-03-12 07:55 UTC
Labels: enhancement
