### ISSUE TITLE
[BUG] Using a non OPENAI model, unable to obtain tokenUsage, tokenUsage was mistakenly removed

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#895] opened 2024-04-08 06:15 UTC
The removal of tokenUsage resulted in incorrect results, and I am unable to modify the isOpenAiModel variable. Although I am not using the OPENAI model, it still returns tokenUsage

Error:
Cannot invoke "dev.langchain4j.model.output.TokenUsage.totalTokenCount()" because the return value of "dev.langchain4j.model.output.Response.tokenUsage()" is null

![image](https://github.com/langchain4j/langchain4j/assets/29765903/aa5e3a54-2f89-4292-b21d-72147124371e)
![image](https://github.com/langchain4j/langchain4j/assets/29765903/c886251c-0c81-43e8-bff8-d8de2b737b59)
![image](https://github.com/langchain4j/langchain4j/assets/29765903/8b8bc874-1839-4607-bf02-77686af552af)

**Please complete the following information:**
- LangChain4j version:0.29.1
- LLM(s) used: zhipu glm-3-turbo
- Java version: 17
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment] 2024-04-09 08:46
Hi, `TokenUsage` is removed from the `Response` for non-OpenAI models _**on purpose**_, because there is no guarantee that it is correct.
Because various LLMs use various tokenizers. `OpenAiStreamingChatModel`, for example, uses `OpenAiTokenizer` to count tokens in the streaming response. I am closing this issue as it is not a bug. Feel free to reopen or open a new proposal if you see a way how to improve this.

**Closed as completed by langchain4j** 2024-04-09 08:46 UTC
Labels: bug

**Comment by yushengliao** [comment] 2024-05-06 00:11
I suggest changing the isOpenAiModel variable to configurable, as there are indeed some models that require it. I hope you can adopt it

**Comment by yushengliao** [comment] 2024-05-06 00:11
I suggest changing the isOpenAiModel variable to configurable, as there are indeed some models that require it. I hope you can adopt it @langchain4j

**Comment by langchain4j** [comment] 2024-05-06 06:42
@yushengliao could you please expand on this? In this case, token cound will be incorrect, right?

**Comment by yushengliao** [comment] 2024-05-07 07:17
> @yushengliao您能详细说明一下吗？这样的话，token cound 就会不正确吧？

I used the glm-3-turbo model API, although it does not belong to OpenAI, the tokenUsage returned by its interface is correct

**Comment by langchain4j** [comment] 2024-05-07 13:06
@yushengliao do they return token usage in **_streaming_** responses? OpenAI, for example, does not return token usage in **_streaming_** responses (only in sync responses), so we calculate it on LC4J side using `OpenAiTokenizer`. And if LLM is using different tokenization algo, it will be incorrect.
