### ISSUE TITLE
[BUG] DefaultPromptTemplateFactory.replaceAll() fails when $ is present in text

### ISSUE THREAD

**Issue by stephanj** [langchain4j/langchain4j#526] opened 2024-01-19 10:11 UTC
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
When you have a $ in your text which is provided to the DefaultPromptTemplateFactory.replaceAll()  

**Log and Stack trace**

```
2024-01-19T09:38:07.737Z: java.lang.IndexOutOfBoundsException: No group 1
2024-01-19T09:38:07.737Z:       at java.base/java.util.regex.Matcher.checkGroup(Matcher.java:1818) ~[na:na]
2024-01-19T09:38:07.737Z:       at java.base/java.util.regex.Matcher.start(Matcher.java:496) ~[na:na]
2024-01-19T09:38:07.737Z:       at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1107) ~[na:na]
2024-01-19T09:38:07.737Z:       at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:1014) ~[na:na]
2024-01-19T09:38:07.737Z:       at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1200) ~[na:na]
2024-01-19T09:38:07.737Z:       at java.base/java.lang.String.replaceAll(String.java:3065) ~[na:na]
2024-01-19T09:38:07.737Z:       at dev.langchain4j.model.input.DefaultPromptTemplateFactory$DefaultTemplate.replaceAll(DefaultPromptTemplateFactory.java:65) ~[langchain4j-core-0.25.0.jar!/:na]
2024-01-19T09:38:07.737Z:       at dev.langchain4j.model.input.DefaultPromptTemplateFactory$DefaultTemplate.render(DefaultPromptTemplateFactory.java:47) ~[langchain4j-core-0.25.0.jar!/:na]
2024-01-19T09:38:07.737Z:       at dev.langchain4j.model.input.PromptTemplate.apply(PromptTemplate.java:80) ~[langchain4j-core-0.25.0.jar!/:na]
2024-01-19T09:38:07.737Z:       at dev.langchain4j.service.DefaultAiServices.prepareUserMessage(DefaultAiServices.java:237) ~[langchain4j-0.25.0.jar!/:na]
2024-01-19T09:38:07.737Z:       at dev.langchain4j.service.DefaultAiServices.access$100(DefaultAiServices.java:35) ~[langchain4j-0.25.0.jar!/:na]
2024-01-19T09:38:07.737Z:       at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:94) ~[langchain4j-0.25.0.jar!/:na]
```

**To Reproduce**
Just include a $ in a text and pass it to a prompt.

**Expected behavior**

```java
private static String replaceAll(String template, String variable, Object value) {
            if (value == null || value.toString() == null) {
                throw illegalArgument("Value for the variable '%s' is null", variable);
            }
            return template.replaceAll(inDoubleCurlyBrackets(variable), value.toString());
        }
```

To fix this issue, you need to escape the $ character in the replacement string or use Matcher.quoteReplacement() method which automatically takes care of such special characters. 

```
return template.replaceAll(inDoubleCurlyBrackets(variable), Matcher.quoteReplacement(value.toString()));
```

**Please complete the following information:**
- LangChain4j version: 0.25.0
- Java version: 21
- Spring Boot version: 3.2.1

**Additional context**

**Comment by langchain4j** [comment] 2024-01-19 10:28
Hi @stephanj, thanks a lot for reporting! Will fix asap and include in the next release.

**Comment by langchain4j** [comment] 2024-01-25 17:42
Has been fixed by https://github.com/langchain4j/langchain4j/pull/545

**Closed as completed by langchain4j** 2024-01-25 17:42 UTC
Labels: bug

**Comment by czp13** [comment] 2024-01-25 18:41
This issue is potentially a duplicate of  #515, or just this issue can be part of #515.
(I need to investigate it).
