### ISSUE TITLE
[BUG] HuggingFaceChatModelIT and HuggingFaceLanguageModelIT failed - Incomplete generation

### ISSUE THREAD

**Issue by gkwan-ibm** [langchain4j/langchain4j#1841] opened 2024-09-26 15:15 UTC
**Describe the bug**
When run test for the langchain4j-hugging-face, I got the following error:

**Log and Stack trace**
```
[INFO] Running dev.langchain4j.model.huggingface.HuggingFaceChatModelIT
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.644 s <<< FAILURE! -- in dev.langchain4j.model.huggingface.HuggingFaceChatModelIT
[ERROR] dev.langchain4j.model.huggingface.HuggingFaceChatModelIT.should_send_messages_and_receive_response -- Time elapsed: 0.569 s <<< ERROR!
java.lang.RuntimeException: status code: 500; body: {"error":"Incomplete generation","error_type":"incomplete_generation"}
	at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.toException(DefaultHuggingFaceClient.java:95)
	at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.generate(DefaultHuggingFaceClient.java:59)
	at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.chat(DefaultHuggingFaceClient.java:47)
	at dev.langchain4j.model.huggingface.HuggingFaceChatModel.generate(HuggingFaceChatModel.java:84)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:44)
	at dev.langchain4j.model.huggingface.HuggingFaceChatModelIT.should_send_messages_and_receive_response(HuggingFaceChatModelIT.java:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] Running dev.langchain4j.model.huggingface.HuggingFaceEmbeddingModelIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.523 s -- in dev.langchain4j.model.huggingface.HuggingFaceEmbeddingModelIT
[INFO] Running dev.langchain4j.model.huggingface.HuggingFaceLanguageModelIT
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.215 s <<< FAILURE! -- in dev.langchain4j.model.huggingface.HuggingFaceLanguageModelIT
[ERROR] dev.langchain4j.model.huggingface.HuggingFaceLanguageModelIT.should_send_prompt_and_receive_response -- Time elapsed: 0.211 s <<< ERROR!
java.lang.RuntimeException: status code: 500; body: {"error":"Incomplete generation","error_type":"incomplete_generation"}
	at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.toException(DefaultHuggingFaceClient.java:95)
	at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.generate(DefaultHuggingFaceClient.java:59)
	at dev.langchain4j.model.huggingface.HuggingFaceLanguageModel.generate(HuggingFaceLanguageModel.java:78)
	at dev.langchain4j.model.huggingface.HuggingFaceLanguageModelIT.should_send_prompt_and_receive_response(HuggingFaceLanguageModelIT.java:28)
	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**To Reproduce**

- clone this repo
- `cd langchain4j-hugging-face`
- `export HF_API_KEY=...`
- `mvn package`
- `mvn verify`

**Expected behavior**

- tests pass

**Please complete the following information:**
- LangChain4j version: latest from the`main` branch
- LLM(s) used: `tiiuae/falcon-7b-instruct` (that is defined in the code)
- Java version:  17
- Spring Boot version (if applicable): 

**Additional context**

**Comment by Martin7-1** [comment] 2024-09-27 03:05
@gkwan-ibm Hi! I think it's huggingface's problem. After changing model to `mistralai/Mistral-7B-Instruct-v0.1` in `HuggingFaceChatModelIT` and `HuggingFaceLanguageModelIT`, the test can pass.

I have yet to find out what the cause of this :)

**Comment by langchain4j** [comment] 2024-10-07 09:26
`HuggingFaceChatModelIT` works again, seems like it was a temporary issue on the HF side, so I am closing this

**Closed as completed by langchain4j** 2024-10-07 09:26 UTC
Labels: bug
