### ISSUE TITLE
[FEATURE] Dynamic Description Injection for POJO Extraction

### ISSUE THREAD

**Issue by fmx0717** [langchain4j/langchain4j#1725] opened 2024-09-07 07:00 UTC
I am working on extracting POJOs (Plain Old Java Objects) from text and I'm referencing the 'POJO_With_Descriptions_Extracting_AI_Service_Example'. However, when using the @Description annotation, I want to support an @V approach to inject into the specified field's @Description. For example, @Description("each step should be described in {{num}} words, steps should rhyme"). I want 'num' to be dynamically specified.

**Comment by cardsharp** [comment] 2024-09-11 02:18
I don't know if this is a workaround or not, but since @Description describes an individual property on the POJO, can't you already accomplish this in the AI service interface via a @UserMessage?

Example:

class MyPojo {
  @Description("Color of fish")
  String color;
}

interface AiAnalysis {
  @UserMessage("Analyze fish types in {{text}} restrict the responses to {{num}} fish types")
  List<MyPojo> analyze(@V("text") String text, @V("num") Integer num)
}

**Comment by langchain4j** [comment] 2024-11-07 14:07
duplicate of https://github.com/langchain4j/langchain4j/issues/706

**Closed as completed by langchain4j** 2024-11-07 14:07 UTC
Labels: enhancement, P3, Structured Outputs
