### ISSUE TITLE
[BUG] Can't store in milvus db v2.4.5

### ISSUE THREAD

**Issue by AbdullahGheith** [langchain4j/langchain4j#1382] opened 2024-07-01 21:34 UTC
**Describe the bug**
Can't save data because its expecting id to be auto generated

**Log and Stack trace**
```
.RequestToMilvusFailedException: Request to Milvus DB failed. Response status:'-5'.

...

Caused by: io.milvus.exception.ParamException: The primary key: id is auto generated, no need to input.

```

**To Reproduce**
Simply trying to save textsegments in milvus using code like:

Connect to db:
```
embeddingStore = MilvusEmbeddingStore.builder()
					.host(getMilvusHost())
					.port(19530)
					.collectionName("mycoll")
					.dimension(1536)
					.build();
```

Save data:

```
List<Embedding> embeddings = new ArrayList<>();
List<TextSegment> textSegments = new ArrayList<>();
embeddings.add(embeddingModel.embed("Test data").content());
textSegments.add("Test data");
embeddingStore.addAll(embeddings, textSegments);
```

**Expected behavior**
Does langchain4j auto generate ids? If so, i needs to disable id generation on collection creation

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: TEXT_EMBEDDING_ADA_002 and gpt4o
- Java version:  17

**Comment by langchain4j** [comment] 2024-07-02 11:19
@AbdullahGheith thank y lot for reporting!

Unfortunately I can't reproduce this issue, could you please share the complete example so I can run it?

**Comment by AbdullahGheith** [comment] 2024-07-02 11:23
Sorry i figured it out. 
I noticed that the auto id is hardcoded to false [here](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/CollectionOperationsExecutor.java#L53)

So i knew that it must have something to do with the way that my collection was created. Indeed, it was created by someone else rather than by langchain4j.

**Comment by langchain4j** [comment] 2024-07-02 11:24
@AbdullahGheith got it, then I am closing this issue

**Closed as completed by langchain4j** 2024-07-02 11:24 UTC
Labels: bug
